CREATE TABLE users( 
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	PasswordHash NVARCHAR(255) NOT NULL,
	Email NVARCHAR(100) NOT NULL UNIQUE,
	Registered DATETIME NOT NULL,
);

CREATE TABLE roles(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(50) NOT NULL,
);

CREATE TABLE projects(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	Title NVARCHAR(50) NOT NULL,
	Description TEXT,
	Created DATETIME NOT NULL,
	Updated DATETIME NOT NULL,
);

CREATE TABLE participants(
	Id INT PRIMARY KEY IDENTITY,
	UserId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES users(Id) ON DELETE CASCADE,
	ProjectId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES projects(Id) ON DELETE CASCADE,
	RoleId INT NOT NULL FOREIGN KEY REFERENCES roles(Id) ON DELETE CASCADE
);

CREATE TABLE projectLists(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	Title NVARCHAR(50) NOT NULL,
	Position INT NOT NULL,
	ProjectId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES projects(Id)
);

CREATE TABLE priorities(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(50) NOT NULL,
	Lvl INT UNIQUE NOT NULL,
);

CREATE TABLE issueTypes(
	Id INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(50)
);

CREATE TABLE issues(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	Title NVARCHAR(50) NOT NULL,
	Description TEXT,
	Created DATETIME NOT NULL,
	Updated DATETIME NOT NULL,
	DueDate DATETIME,
	Position INT NOT NULL,
	TimeEstimate INT,
	TimeSpent INT,
	ProjectId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES projects(Id) ON DELETE CASCADE,
	ProjectListId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES projectLists(Id) ON DELETE CASCADE,
	UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES users(Id) ON DELETE SET NULL,
	PriorityId INT FOREIGN KEY REFERENCES priorities(Id) ON DELETE SET NULL,
	ParentIssueId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES issues(Id),
	IssueTypeId INT FOREIGN KEY REFERENCES issueTypes(Id)
);

CREATE TABLE assignedPeople(
	Id INT IDENTITY PRIMARY KEY,
	IssueId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES issues(Id) ON DELETE CASCADE,
	UserId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES users(Id) ON DELETE CASCADE
);	

CREATE TABLE comments(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	Content TEXT NOT NULL,
	Created DATETIME NOT NULL,
	Updated DATETIME NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES users(Id) ON DELETE CASCADE,
	IssueId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES issues(Id) ON DELETE CASCADE
);

CREATE TABLE notifications(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	Content TEXT NOT NULL,
	Created DATETIME NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES users(Id), -- Akinek szól, lehet üres, akkor sima audit log
	ModifierId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES users(Id), -- Módosító neve
	ProjectId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES projects(Id) ON DELETE CASCADE,
);

CREATE TABLE auditLogs(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	UserId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES users(Id),
	Created DATETIME NOT NULL,
	Content TEXT NOT NULL,
	ProjectId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES projects(Id) ON DELETE CASCADE,
)

--insert into issueTypes (Name) VALUES
--('Task'), ('Story'), ('Bug'), ('Subtask')

--insert into roles (Name) VALUES
--('Owner'), ('Member')

--insert into priorities (Name, Lvl)
--Values
--('Legalacsonyabb', 1), ('Alacsony', 2), ('Közepes', 3), ('Magas', 4), ('Legmagasabb', 5)

CREATE PROCEDURE DeleteProjectAndLists
    @ProjectId UNIQUEIDENTIFIER
AS
BEGIN
    DELETE FROM projectLists
    WHERE ProjectId = @ProjectId;
END;